services:
  # Backend API Service
  - type: web
    name: digitaliulm-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: ./server
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
