services:
  # Backend API Service
  - type: web
    name: digitaliulm-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
